# Generated by Django 4.2.5 on 2023-10-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newpost', '0002_sportnews_tsport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportnews',
            name='tsport',
            field=models.PositiveSmallIntegerField(choices=[(1, 'футбол'), (2, 'хоккей'), (3, 'баскетбол'), (4, 'теннис'), (5, 'волейбол'), (6, 'бокс')], verbose_name='tsport'),
        ),
    ]
